#!sh

# /**
#  *
#  *   This program is free software; you can redistribute it and/or#  * modify it under the terms of the GNU General Public License#  * as published by the Free Software Foundation; either version 2#  * of the License, or (at your option) any later version.#  *#  *   This program is distributed in the hope that it will be useful,#  * but WITHOUT ANY WARRANTY; without even the implied warranty of#  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#  * GNU General Public License for more details.#  *#  *   You should have received a copy of the GNU General Public License#  * along with this program; if not, write to the Free Software#  * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#  *
#  */

# $1 est le répertoire contenant les fichiers à analyser
clear
for x in $1/* ; do
	echo "Mise en forme du document : " $x
	./dec $x
	echo "Analyse Perl" $x'd' $x'.xml'
	./entitetemporelle $x'd' $x'.xml'
	echo "Post-traitement PHP"
	php ./timex2iso8601.php $x
	rm $x'd'
	rm $x'.xml'
done 

# (c) E. Desmontils, LINA, 2013